version: "3.9"
services:
  py-backend:
    build: ./backend
    ports:
      - "8000:8000"

  py-frontend:
    build: ./frontend
    ports:
      - "8501:8501"

  py-database:
    build: ./database
    ports:
      - "5000:5000"
